const BOARD = {
  COMMON: {
    RESULTS,
    LETTER_AXES,
    CELL_STATUS: GRID.TRACKING.STATUS_VALUES
  },
  CLASSES: {
    GRIDS: {
      MAIN: GRID.COMMON.CLASSES.GRID_TYPES.MAIN,
      TRACKING: GRID.COMMON.CLASSES.GRID_TYPES.TRACKING,
      AI_DISPLAY: 'ai-display-tracking-grid',
      MAIN_GRID_HIT: GRID.MAIN.CLASSES.HIT_MARKER,
      TRACKING_WRAPPER: GRID.TRACKING.CLASSES.WRAPPER,
      CELL: GRID.COMMON.CLASSES.CELL
    },
    FLEETS: {
      MAIN_LIST: FLEET_LIST.COMMON.CLASSES.FLEET_LIST_TYPES.MAIN,
      TRACKING_LIST: FLEET_LIST.COMMON.CLASSES.FLEET_LIST_TYPES.TRACKING
    },
    PLAYER_IDS: {
      P1: PLAYERS.IDS.P1,
      P2: PLAYERS.IDS.P2
    }
  },
  ATTRIBUTES: {
    ASSIGNED_PLAYER_ID: ELEMENT_ATTRIBUTES.DATA('player')
  },
  EVENTS: {
    PLAYER_ATTACKED: 'playerAttacked'
  },
  SELECTORS: {
    GRIDS: GRID_SELECTORS
  }
};
